import React, { useEffect, useMemo, useState } from "react";
import { NavLink, useLocation, useNavigate } from "react-router-dom";
import { FiActivity, FiArrowRight, FiCalendar, FiCheckCircle, FiChevronDown, FiCreditCard, FiEdit3, FiGrid, FiLogOut, FiMapPin, FiSearch, FiSettings, FiShield, FiShoppingBag, FiTag, FiUser, FiX } from "react-icons/fi";
import { clearToken, getToken } from "../services/auth";

const API = import.meta.env.VITE_API_URL || "";
const imageUrl = (image) => !image ? "" : /^https?:\/\//.test(image) ? image : `${API.replace(/\/$/, "")}${image.startsWith("/") ? image : `/uploads/${image}`}`;
const titleOf = (booking) => booking?.event?.title || booking?.eventName || "Untitled event";
const dateOf = (booking) => new Date(booking?.event?.date || booking?.eventDate || 0).valueOf() || 0;
const dateText = (value) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Date pending";
const quantityOf = (booking) => Number(booking?.ticketCount ?? booking?.tickets ?? 1);
const totalOf = (booking) => Number(booking?.totalAmount ?? booking?.totalPrice ?? quantityOf(booking) * (booking?.event?.price || 0)) || 0;

function Status({ value }) {
  const status = value || "Pending";
  const tone = ["Confirmed", "Approved", "Active"].includes(status) ? "success" : ["Cancelled", "Rejected"].includes(status) ? "danger" : "pending";
  return <span className={`status-badge status-${tone}`}><span aria-hidden="true">●</span>{status}</span>;
}
function Avatar({ user, large = false }) {
  const initials = (user?.name || user?.email || "U").split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  return user?.avatar ? <img className={`profile-avatar ${large ? "profile-avatar-large" : ""}`} src={imageUrl(user.avatar)} alt={user.name || "Profile"} /> : <div className={`profile-avatar ${large ? "profile-avatar-large" : ""}`}>{initials}</div>;
}
function EmptyState({ icon: Icon = FiActivity, title, children }) { return <div className="empty-state">{React.createElement(Icon, { size: 25 })}<strong>{title}</strong>{children}</div>; }
function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal-panel" role="dialog" aria-modal="true"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><FiX /></button></div>{children}</div></div>; }
function Panel({ title, icon: Icon = FiActivity, children }) { return <section className="dashboard-panel"><div className="panel-heading"><h2>{title}</h2>{React.createElement(Icon)}</div>{children}</section>; }
function Info({ label, value }) { return <div className="info-line"><span>{label}</span><strong>{value || "Not available"}</strong></div>; }
function BookingRow({ booking }) { return <article className="booking-row"><div className="event-thumb">{imageUrl(booking.event?.image) ? <img src={imageUrl(booking.event.image)} alt="" /> : <FiCalendar />}</div><div className="booking-main"><strong>{titleOf(booking)}</strong><span><FiCalendar />{dateText(booking.event?.date || booking.eventDate)} <FiMapPin />{booking.event?.location || booking.location || "Venue pending"}</span><small>#{String(booking._id || "").slice(-8)} · {quantityOf(booking)} ticket{quantityOf(booking) === 1 ? "" : "s"}</small></div><Status value={booking.bookingStatus} /></article>; }

export default function Profile() {
  const token = getToken(); const location = useLocation(); const navigate = useNavigate();
  const section = location.pathname.split("/")[2] || "overview";
  const [user, setUser] = useState(null); const [bookings, setBookings] = useState([]); const [sellTickets, setSellTickets] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [mobileNav, setMobileNav] = useState(false);
  const [editOpen, setEditOpen] = useState(false); const [logoutOpen, setLogoutOpen] = useState(false); const [toast, setToast] = useState("");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All"); const [sort, setSort] = useState("newest");
  const loadData = async () => {
    setLoading(true); setError("");
    try {
      const headers = { Authorization: `Bearer ${token}` };
      const [profileResponse, bookingResponse, sellingResponse] = await Promise.all([fetch(`${API}/api/users/profile`, { headers }), fetch(`${API}/api/bookings/my`, { headers }), fetch(`${API}/api/sell-ticket/my`, { headers })]);
      if (!profileResponse.ok) throw new Error("Unable to load your account");
      const profile = await profileResponse.json(); setUser(profile); setName(profile.name || ""); setEmail(profile.email || "");
      setBookings(bookingResponse.ok ? await bookingResponse.json() : []); setSellTickets(sellingResponse.ok ? await sellingResponse.json() : []);
    } catch (loadError) { setError(loadError.message || "Something went wrong."); } finally { setLoading(false); }
  };
  // The retry action reuses loadData; token is the intended fetch boundary.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { loadData(); }, [token]);
  useEffect(() => { if (!toast) return undefined; const timer = setTimeout(() => setToast(""), 3500); return () => clearTimeout(timer); }, [toast]);
  const upcoming = useMemo(() => bookings.filter((booking) => dateOf(booking) >= Date.now() && booking.bookingStatus !== "Cancelled").sort((a, b) => dateOf(a) - dateOf(b)), [bookings]);
  const filtered = useMemo(() => bookings.filter((booking) => `${titleOf(booking)} ${booking.event?.location || booking.location || ""} ${booking._id || ""}`.toLowerCase().includes(query.toLowerCase()) && (filter === "All" || (booking.bookingStatus || "Pending") === filter)).sort((a, b) => sort === "oldest" ? dateOf(a) - dateOf(b) : dateOf(b) - dateOf(a)), [bookings, query, filter, sort]);
  const stats = [["Total bookings", bookings.length, FiCreditCard], ["Upcoming events", upcoming.length, FiCalendar], ["Tickets purchased", bookings.reduce((sum, booking) => sum + quantityOf(booking), 0), FiTag], ["Events attended", bookings.filter((booking) => dateOf(booking) < Date.now() && booking.bookingStatus !== "Cancelled").length, FiCheckCircle]];
  const navItems = [{ key: "overview", label: "Overview", icon: FiGrid }, { key: "profile", label: "My Profile", icon: FiUser }, { key: "bookings", label: "My Bookings", icon: FiCreditCard }, { key: "tickets", label: "My Tickets", icon: FiTag }, { key: "selling", label: "Sell Ticket Activity", icon: FiShoppingBag }, { key: "settings", label: "Account Settings", icon: FiSettings }];
  const updateProfile = async (event) => {
    event.preventDefault(); if (!name.trim() || !email.trim()) return setToast("Name and email are required.");
    try { const response = await fetch(`${API}/api/users/profile`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ name: name.trim(), email: email.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Profile update failed"); setUser(data); setEditOpen(false); setToast("Profile updated successfully."); } catch (updateError) { setToast(updateError.message || "Something went wrong. Please try again."); }
  };
  if (loading) return <main className="profile-shell"><div className="profile-loading"><div /><div /><div /></div></main>;
  if (error) return <main className="profile-shell"><div className="account-error"><FiActivity size={28} /><h1>Something went wrong.</h1><p>{error}</p><button className="primary-button" onClick={loadData}>Try Again</button></div></main>;
  const firstName = (user?.name || "there").split(" ")[0];
  const content = section === "profile" ? <ProfileView user={user} onEdit={() => setEditOpen(true)} /> : section === "bookings" ? <BookingsView bookings={filtered} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} sort={sort} setSort={setSort} /> : section === "tickets" ? <TicketsView bookings={bookings} /> : section === "selling" ? <SellingView tickets={sellTickets} /> : section === "settings" ? <SettingsView user={user} onEdit={() => setEditOpen(true)} onLogout={() => setLogoutOpen(true)} /> : <Overview upcoming={upcoming} bookings={bookings} stats={stats} navigate={navigate} />;
  return <main className="profile-shell"><div className="profile-layout"><aside className={`profile-sidebar ${mobileNav ? "is-open" : ""}`}><div className="sidebar-identity"><Avatar user={user} /><div><strong>{user?.name || "Eventify member"}</strong><span>{user?.email}</span></div><span className="role-badge">{user?.role || "member"}</span></div><button className="mobile-nav-toggle" onClick={() => setMobileNav(!mobileNav)}>Navigate account <FiChevronDown /></button><nav className="profile-nav" aria-label="Account navigation">{navItems.map(({ key, label, icon: Icon }) => <NavLink key={key} to={`/profile/${key}`} onClick={() => setMobileNav(false)} className={({ isActive }) => isActive ? "active" : ""}>{React.createElement(Icon)}{label}</NavLink>)}<span className="nav-divider" /><NavLink to="/contact"><FiShield />Help & Support</NavLink><button className="logout-link" onClick={() => setLogoutOpen(true)}><FiLogOut />Logout</button></nav><button className="sidebar-edit" onClick={() => setEditOpen(true)}><FiEdit3 />Edit Profile</button></aside><section className="profile-content"><div className="content-topline"><div><span className="eyebrow">ACCOUNT CENTER</span><h1>{section === "overview" ? `Good morning, ${firstName}` : navItems.find((item) => item.key === section)?.label || "Account"}</h1></div></div>{content}</section></div>{editOpen && <Modal title="Edit your profile" onClose={() => setEditOpen(false)}><form className="edit-form" onSubmit={updateProfile}><label>Full name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditOpen(false)}>Cancel</button><button className="primary-button">Save Changes</button></div></form></Modal>}{logoutOpen && <Modal title="Sign out of Eventify?" onClose={() => setLogoutOpen(false)}><p className="modal-copy">You can sign back in anytime to access your bookings and tickets.</p><div className="modal-actions"><button className="secondary-button" onClick={() => setLogoutOpen(false)}>Cancel</button><button className="danger-button" onClick={() => { clearToken(); navigate("/login"); }}>Logout</button></div></Modal>}{toast && <div className="toast" role="status">{toast}</div>}</main>;
}

function Overview({ upcoming, bookings, stats, navigate }) {
  return <div className="dashboard-view"><p className="subheading">Here&apos;s what&apos;s happening with your Eventify account.</p><div className="stats-grid">{stats.map(([label, value, Icon]) => <div className="stat-card" key={label}><div className="stat-icon">{React.createElement(Icon)}</div><span>{label}</span><strong>{value}</strong></div>)}</div><div className="overview-grid"><Panel title="Recent activity"><div className="activity-list">{bookings.length ? bookings.slice(0, 5).map((booking) => <div className="activity-row" key={booking._id}><span className="activity-dot"><FiCheckCircle /></span><div><strong>Booking {booking.bookingStatus || "created"}</strong><span>{titleOf(booking)}</span></div><time>{dateText(booking.createdAt || booking.eventDate)}</time><Status value={booking.bookingStatus} /></div>) : <EmptyState title="No recent activity yet." />}</div></Panel><Panel title="Upcoming bookings" icon={FiCalendar}><button className="text-button" onClick={() => navigate("/profile/bookings")}>View all <FiArrowRight /></button>{upcoming.slice(0, 3).map((booking) => <BookingRow booking={booking} key={booking._id} />)}{!upcoming.length && <EmptyState title="You haven&apos;t booked any upcoming events yet." icon={FiCalendar}><NavLink className="text-button" to="/events">Explore Events <FiArrowRight /></NavLink></EmptyState>}</Panel></div></div>;
}
function BookingsView({ bookings, query, setQuery, filter, setFilter, sort, setSort }) {
  return <div className="dashboard-view"><div className="toolbar"><label className="search-field"><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search bookings, venues or IDs" aria-label="Search bookings" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All</option><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div><Panel title="Booking history" icon={FiCreditCard}>{bookings.length ? bookings.map((booking) => <BookingRow booking={booking} key={booking._id} />) : <EmptyState title="No bookings yet." icon={FiCreditCard}><NavLink className="text-button" to="/events">Explore Events <FiArrowRight /></NavLink></EmptyState>}</Panel></div>;
}
function TicketsView({ bookings }) {
  const confirmed = bookings.filter((booking) => booking.bookingStatus === "Confirmed");
  return <div className="dashboard-view"><p className="subheading">Your confirmed passes, ready when you are.</p><div className="ticket-grid">{confirmed.map((booking) => <article className="digital-ticket" key={booking._id}><div className="ticket-image">{imageUrl(booking.event?.image) ? <img src={imageUrl(booking.event.image)} alt="" /> : <FiTag />}</div><div className="ticket-details"><span className="eyebrow">EVENTIFY PASS</span><h2>{titleOf(booking)}</h2><p><FiCalendar />{dateText(booking.event?.date || booking.eventDate)} · {booking.event?.time || "Time pending"}</p><p><FiMapPin />{booking.event?.location || booking.location || "Venue pending"}</p><div className="ticket-meta"><span>Ticket type<strong>General admission</strong></span><span>Quantity<strong>{quantityOf(booking)}</strong></span><span>Booking ID<strong>#{String(booking._id).slice(-8)}</strong></span></div></div><div className="ticket-status"><Status value={booking.bookingStatus} /><span>₹ {totalOf(booking).toLocaleString()}</span></div></article>)}{!confirmed.length && <EmptyState title="No confirmed tickets yet." icon={FiTag}><NavLink className="text-button" to="/events">Find an event <FiArrowRight /></NavLink></EmptyState>}</div></div>;
}
function ProfileView({ user, onEdit }) {
  return <div className="dashboard-view"><section className="profile-intro"><Avatar user={user} large /><div><span className="eyebrow">PERSONAL PROFILE</span><h2>{user?.name}</h2><p>{user?.email}</p><Status value={user?.status === "active" ? "Active" : user?.status} /></div><button className="primary-button" onClick={onEdit}><FiEdit3 />Edit Profile</button></section><div className="info-grid"><Panel title="Personal information" icon={FiUser}><Info label="Full name" value={user?.name} /><Info label="Email address" value={user?.email} /><Info label="Phone" value={user?.phone || "Not added"} /></Panel><Panel title="Account information" icon={FiShield}><Info label="Role" value={user?.role || "member"} /><Info label="Account status" value={user?.status || "active"} /><Info label="Joined" value={dateText(user?.createdAt)} /></Panel></div></div>;
}
function SellingView({ tickets }) {
  return <div className="dashboard-view"><p className="subheading">Track the ticket resale requests you have submitted.</p><Panel title="Selling activity" icon={FiShoppingBag}>{tickets.length ? tickets.map((ticket) => <div className="activity-row" key={ticket._id}><span className="activity-dot"><FiShoppingBag /></span><div><strong>{ticket.eventName}</strong><span>{dateText(ticket.eventDate)} · Expected ₹{Number(ticket.expectedPrice || 0).toLocaleString()}</span></div><time>{dateText(ticket.createdAt)}</time><Status value={ticket.status} /></div>) : <EmptyState title="No ticket sale requests yet." icon={FiShoppingBag}><NavLink className="text-button" to="/sell-ticket">Sell Your Tickets <FiArrowRight /></NavLink></EmptyState>}</Panel></div>;
}
function SettingsView({ user, onEdit, onLogout }) {
  return <div className="dashboard-view"><Panel title="Account settings" icon={FiSettings}><Info label="Name" value={user?.name} /><Info label="Email" value={user?.email} /><div className="setting-action"><span><strong>Profile details</strong><small>Keep your contact information current.</small></span><button className="secondary-button" onClick={onEdit}>Edit profile</button></div></Panel><section className="dashboard-panel danger-zone"><div><span className="eyebrow">SESSION</span><h2>Sign out</h2><p>End your current Eventify session on this device.</p></div><button className="danger-button" onClick={onLogout}><FiLogOut />Logout</button></section></div>;
}
